### ISSUE TITLE
Git repository urls in urls.txt

### ISSUE THREAD

**Issue by kmeaw** [stal-ix/ix#175]
pkgs/die/scripts/urls.txt contains ~50 of git repositories that are being constantly updated on the mirrors - git web frontends are serving the index page. Probably a tree snapshot URL should be used instead (or git fetching should be implemented in pkgs/die/scripts/recache)

Here is a [list of recently downloaded](https://github.com/stal-ix/ix/files/12575456/git.txt) files.

**Comment by pg83** [comment]
My process of finding new urls is not very precise, it is more aimed at completeness. Bad urls will be downloaded once, and will not interfere in the future.

https://github.com/pg83/ix/blob/main/pkgs/die/scripts/urls

**Comment by adouche** [comment]
@kmeaw, we give merch to the first maintainers. I couldn't find contacts. To receive a stal/IX t-shirt [contact me](https://t.me/kperfilieva).

**Comment by kmeaw** [comment]
I don't have a Telegram account. You can reach be by email (it's in the commit's "author" line) or Jabber.
