### ISSUE TITLE
Relationship between Nix and this project

### ISSUE THREAD

**Issue by ShamrockLee** [stal-ix/ix#77]
[Nix](https://github.com/NixOS/nix) is a declarative, reproducible package manager based on [a PhD thesis](https://www.researchgate.net/publication/220900529_Nix_A_Safe_and_Policy-Free_System_for_Software_Deployment) by Eelco Dolstra et. al. published in 2004. It operates its `/nix/store` filled with hashed paths -- just like IX.

Is this project based on / inspired by Nix? What is the key difference and improvement? It would be good to add it to README.

**Comment by pg83** [comment]
Tecnically IX uses similar FS layout, as Nix/Guix(and many other modern package managers).

I can't really say that IX based or inspired by Nix, cause they have in common only FS layout (and, in IX case, it is inspired by our corporate private build system).

**Comment by pg83** [comment]
IX have a new fresh package base, build on top of python + Jinja2 stack, we do not provide user's home management.
Name "IX" just shortest useful suffix of word UNIX.

**Comment by ShamrockLee** [comment]
Cool! Thanks for your answer. It's surprising to know that the garlic-like fs layout is already used by package managers aside from Nix and Guix.
